# Generated by Django 3.0.2 on 2020-02-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_popular_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='month',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
