# Generated by Django 3.0.2 on 2020-02-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social',
            field=models.BooleanField(default=False),
        ),
    ]
