# Generated by Django 3.0.2 on 2020-02-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='article_no',
            field=models.IntegerField(null=True),
        ),
    ]
