# Generated by Django 3.0.2 on 2020-02-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification_article_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='nickname',
            field=models.IntegerField(),
        ),
    ]
