# Generated by Django 3.0.2 on 2020-02-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200219_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_user',
            field=models.IntegerField(),
        ),
    ]
